minor fixes

diff --git a/dns_client b/dns_client
--- a/dns_client
+++ b/dns_client
@@ -22,7 +22,7 @@
 source blib
 eval "$B_SCRIPT"
 
-source "$B_SCRIPT_DIR/dnsCommon" || { B_ERR="Failed to source the common code." ; B_E }
+source "$B_SCRIPT_DIR/dnsCommon" || { B_ERR="Failed to source the common code." ; B_E ; }
 
 #name of the iptables chain created by this script
 IPT_FILTER_CHAIN="dns_client_filter"
@@ -42,7 +42,7 @@ exit 1
 
 function assertFirewallService {
 #cf. https://github.com/QubesOS/qubes-issues/issues/3269 why it's good to check the firewall service is up
-systemctl status qubes-firewall > /dev/null || { B_ERR="The qubes-firewall service appears to be down! This is certainly an issue. Please investigate!" ; B_E }
+systemctl status qubes-firewall > /dev/null || { B_ERR="The qubes-firewall service appears to be down! This is certainly an issue. Please investigate!" ; B_E ; }
 }
 
 function log {
@@ -58,31 +58,31 @@ log "setup started..."
 assertFirewallService
 
 #update /etc/resolv.conf
-cp -f "$RESOLV" "$RESOLV.bak" || { B_ERR="Failed to copy $RESOLV." ; B_E }
-echo "nameserver $dnsServer" > "$RESOLV" || { B_ERR="Failed to write to $RESOLV." ; B_E }
+cp -f "$RESOLV" "$RESOLV.bak" || { B_ERR="Failed to copy $RESOLV." ; B_E ; }
+echo "nameserver $dnsServer" > "$RESOLV" || { B_ERR="Failed to write to $RESOLV." ; B_E ; }
 
 #make sure the DNS server changes are reflected by the Qubes DNAT rules
 #NOTE: currently not really needed as we do our own DNAT below
-#/usr/lib/qubes/qubes-setup-dnat-to-ns || { B_ERR="Failed to setup the Qubes OS DNAT rules. Not run inside a proxy VM?" ; B_E }
+#/usr/lib/qubes/qubes-setup-dnat-to-ns || { B_ERR="Failed to setup the Qubes OS DNAT rules. Not run inside a proxy VM?" ; B_E ; }
 
 #FORCE usage of the DNS server regardless of what DNS server the upstream VMs are using
 #prevents misconfigured clients
 #prevents malware or strange client implementations from playing with custom DNS servers
-iptables -t nat -N "$IPT_NAT_CHAIN" || { B_ERR="Failed to create the iptables NAT chain $IPT_NAT_CHAIN. Maybe it already exists?" ; B_E }
+iptables -t nat -N "$IPT_NAT_CHAIN" || { B_ERR="Failed to create the iptables NAT chain $IPT_NAT_CHAIN. Maybe it already exists?" ; B_E ; }
 ( set -e
-  iptables -t nat -A "$IPT_NAT_CHAIN" ! -s $dnsServer ! -d $dnsServer -p udp --dport 53 -j DNAT --to ${dnsServer}:53
-  iptables -t nat -A "$IPT_NAT_CHAIN" ! -s $dnsServer ! -d $dnsServer -p tcp --dport 53 -j DNAT --to ${dnsServer}:53
+  iptables -t nat -A "$IPT_NAT_CHAIN" ! -s "$dnsServer" ! -d "$dnsServer" -p udp --dport 53 -j DNAT --to "${dnsServer}:53"
+  iptables -t nat -A "$IPT_NAT_CHAIN" ! -s "$dnsServer" ! -d "$dnsServer" -p tcp --dport 53 -j DNAT --to "${dnsServer}:53"
   iptables -t nat -I PREROUTING -j "$IPT_NAT_CHAIN"
 )
 [ $? -ne 0 ] && B_ERR="Failed to setup some of the iptables DNAT rules. Please investigate!" && B_E
 
 #allow traffic to the DNS server from other VMs and the other way around
-iptables -N "$IPT_FILTER_CHAIN" || { B_ERR="Failed to create the iptables FILTER chain $IPT_FILTER_CHAIN. Maybe it already exists?" ; B_E }
+iptables -N "$IPT_FILTER_CHAIN" || { B_ERR="Failed to create the iptables FILTER chain $IPT_FILTER_CHAIN. Maybe it already exists?" ; B_E ; }
 ( set -e
-  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -d $dnsServer/32 -p tcp --dport 53 -j ACCEPT
-  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -d $dnsServer/32 -p udp --dport 53 -j ACCEPT
-  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -s $dnsServer/32 -p tcp --sport 53 -j ACCEPT
-  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -s $dnsServer/32 -p tcp --sport 53 -j ACCEPT
+  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -d "$dnsServer/32" -p tcp --dport 53 -j ACCEPT
+  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -d "$dnsServer/32" -p udp --dport 53 -j ACCEPT
+  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -s "$dnsServer/32" -p tcp --sport 53 -j ACCEPT
+  iptables -A "$IPT_FILTER_CHAIN" -i vif+ -o vif+ -s "$dnsServer/32" -p tcp --sport 53 -j ACCEPT
 )
 [ $? -ne 0 ] && B_ERR="Failed to setup some of the iptables FILTER rules. Please investigate!" && B_E
 
@@ -95,7 +95,7 @@ iptables -N "$IPT_FILTER_CHAIN" || { B_ERR="Failed to create the iptables FILTER
 # [...]
 #NOTE: this is fully compatible to the VPN installForwardDropDefaultRule() - the order in which any of them is executed doesn't matter (only both changes at the same time wouldn't be good, but the DNS VM is meant to be started only after the VPN is up anyway)
 local ipt rule rules
-ipt="$(iptables-save)" || { B_ERR="Failed to get the iptables rules." ; B_E }
+ipt="$(iptables-save)" || { B_ERR="Failed to get the iptables rules." ; B_E ; }
 rules=""
 local found=1
 while IFS= read -r rule ; do
@@ -105,8 +105,8 @@ while IFS= read -r rule ; do
   fi
   rules="$rules"$'\n'"$rule"
 done <<< "$ipt"
-[ $found -eq 0 ] || { B_ERR="Didn't find the location to add the custom iptables rule. Programming mistake?! Please investigate!" ; B_E }
-iptables-restore <<< "$rules" || { B_ERR="Failed to set the iptables rules." ; B_E }
+[ $found -eq 0 ] || { B_ERR="Didn't find the location to add the custom iptables rule. Programming mistake?! Please investigate!" ; B_E ; }
+iptables-restore <<< "$rules" || { B_ERR="Failed to set the iptables rules." ; B_E ; }
 
 log "setup done"
 return 0
@@ -121,14 +121,14 @@ log "firewall-update started..."
 #NOTE:
 #we may be called during setup() --> we silently quit our checks then
 local uptime=
-uptime="$(grep -E -o '^[0-9]+' /proc/uptime)" || { B_ERR="Failed to identify the uptime!" ; B_E }
+uptime="$(grep -E -o '^[0-9]+' /proc/uptime)" || { B_ERR="Failed to identify the uptime!" ; B_E ; }
 [ $uptime -le 30 ] && log "firewall-update right during/after boot. Skipping..." && return 0
 
 assertFirewallService
 
 #make sure /etc/resolv.conf still contains our server
 local out="$(< $RESOLV)"
-[[ "$out" == "nameserver $dnsServer" ]] || { B_ERR="$RESOLV changed on Qubes OS firewall update. This is unexpected. Please investigate!" ; B_E }
+[[ "$out" == "nameserver $dnsServer" ]] || { B_ERR="$RESOLV changed on Qubes OS firewall update. This is unexpected. Please investigate!" ; B_E ; }
 
 #make sure our custom iptables chains still exists
 iptables -N "$IPT_FILTER_CHAIN" &> /dev/null && B_ERR="$IPT_FILTER_CHAIN had to be recreated on Qubes OS firewall update. That is unexpected.. Please investigate!" && B_E
diff --git a/dns_server b/dns_server
--- a/dns_server
+++ b/dns_server
@@ -26,7 +26,7 @@ eval "$B_SCRIPT"
 
 b_import "proc"
 
-source "$B_SCRIPT_DIR/dnsCommon" || { B_ERR="Failed to source the common code." ; B_E }
+source "$B_SCRIPT_DIR/dnsCommon" || { B_ERR="Failed to source the common code." ; B_E ; }
 
 #name of the unbound user
 #(nowadays not really needed anymore as we don't run inside chroot, but unbound appears to fail otherwise anyway)
@@ -85,18 +85,18 @@ trap stopR EXIT
 
 #copy the DNS root info & root key for DNSSEC
 local dir="${UNBOUND_ROOT_HINTS_TARGET%/*}"
-chown -R "$UNBOUND_USER:$UNBOUND_USER" "$dir" || { B_ERR="Failed to set the ownership for $dir." ; B_E }
-cp -f "$UNBOUND_ROOT_HINTS_SOURCE" "$UNBOUND_ROOT_HINTS_TARGET" || { B_ERR="Failed to copy $UNBOUND_ROOT_HINTS_SOURCE." ; B_E }
-cp -f "$UNBOUND_ROOT_KEYS_SOURCE" "$UNBOUND_ROOT_KEYS_TARGET" || { B_ERR="Failed to copy $UNBOUND_ROOT_KEYS_SOURCE." ; B_E }
+chown -R "$UNBOUND_USER:$UNBOUND_USER" "$dir" || { B_ERR="Failed to set the ownership for $dir." ; B_E ; }
+cp -f "$UNBOUND_ROOT_HINTS_SOURCE" "$UNBOUND_ROOT_HINTS_TARGET" || { B_ERR="Failed to copy $UNBOUND_ROOT_HINTS_SOURCE." ; B_E ; }
+cp -f "$UNBOUND_ROOT_KEYS_SOURCE" "$UNBOUND_ROOT_KEYS_TARGET" || { B_ERR="Failed to copy $UNBOUND_ROOT_KEYS_SOURCE." ; B_E ; }
 
 #notify the user on changes done to the DNs roots by the debian package maintainers
 notifyOnDiff "$UNBOUND_ROOT_KEYS_SOURCE" "$PACKAGE_ROOT_KEYS" "The DNSSEC root.key changed according to the package maintainers. Please investigate!"
 notifyOnDiff "$UNBOUND_ROOT_HINTS_SOURCE" "$PACKAGE_ROOT_HINTS" "The DNSSEC root.hints changed according to the package maintainers. Please investigate!" '^\s*;.*$'
 
 #create a log file that unbound can write to
-touch "$UNBOUND_LOG" || { B_ERR="Failed to create $UNBOUND_LOG" ; B_E }
-chown "$UNBOUND_USER:$UNBOUND_USER" "$UNBOUND_LOG" || { B_ERR="Failed to pass ownership of the $UNBOUND_LOG." ; B_E }
-chmod 664 "$UNBOUND_LOG" || { B_ERR="Failed to chmod $UNBOUND_LOG." ; B_E }
+touch "$UNBOUND_LOG" || { B_ERR="Failed to create $UNBOUND_LOG" ; B_E ; }
+chown "$UNBOUND_USER:$UNBOUND_USER" "$UNBOUND_LOG" || { B_ERR="Failed to pass ownership of the $UNBOUND_LOG." ; B_E ; }
+chmod 664 "$UNBOUND_LOG" || { B_ERR="Failed to chmod $UNBOUND_LOG." ; B_E ; }
 
 #wait for the wait file to disappear
 while [ -f "$WAIT_FILE" ] ; do
@@ -105,7 +105,7 @@ while [ -f "$WAIT_FILE" ] ; do
 done
 
 #start unbound
-unbound -c "$UNBOUND_CONF" || { B_ERR="Failed to start unbound. You might need to fix your config file?!" ; B_E }
+unbound -c "$UNBOUND_CONF" || { B_ERR="Failed to start unbound. You might need to fix your config file?!" ; B_E ; }
 setLocalDNSServer
 allowDNSOnFirewall
 
@@ -163,14 +163,14 @@ return 0
 
 function setLocalDNSServer {
 if [ ! -e "$RESOLV_BAK" ] ; then
-  cp -f "$RESOLV" "$RESOLV_BAK" || { B_ERR="Failed to restore $RESOLV_BAK --> $RESOLV" ; B_E }
+  cp -f "$RESOLV" "$RESOLV_BAK" || { B_ERR="Failed to restore $RESOLV_BAK --> $RESOLV" ; B_E ; }
 fi
-echo "127.0.0.1" > "$RESOLV" || { B_ERR="Failed to write to $RESOLV" ; B_E }
+echo "127.0.0.1" > "$RESOLV" || { B_ERR="Failed to write to $RESOLV" ; B_E ; }
 }
 
 function restoreLocalDNSServer {
 if [ -f "$RESOLV_BAK" ] ; then
-  cp -f "$RESOLV_BAK" "$RESOLV" || { B_ERR="Failed to restore $RESOLV_BAK --> $RESOLV" ; B_E }
+  cp -f "$RESOLV_BAK" "$RESOLV" || { B_ERR="Failed to restore $RESOLV_BAK --> $RESOLV" ; B_E ; }
 fi
 return 0
 }
@@ -180,12 +180,12 @@ function allowDNSOnFirewall {
 #put all unbound-specific rules to a dedicated chain
 #we only re-create it, if it's not already there
 if iptables -N "$IPT_CHAIN" 2> /dev/null ; then
-  iptables -I INPUT -j "$IPT_CHAIN" || { B_ERR="iptables issue." ; B_E }
+  iptables -I INPUT -j "$IPT_CHAIN" || { B_ERR="iptables issue." ; B_E ; }
 fi
 
 iptables -F "$IPT_CHAIN"
-iptables -A "$IPT_CHAIN" -i eth0 -p udp --dport 53 -j ACCEPT || { B_ERR="iptables issue." ; B_E }
-iptables -A "$IPT_CHAIN" -i eth0 -p tcp --dport 53 -j ACCEPT || { B_ERR="iptables issue." ; B_E }
+iptables -A "$IPT_CHAIN" -i eth0 -p udp --dport 53 -j ACCEPT || { B_ERR="iptables issue." ; B_E ; }
+iptables -A "$IPT_CHAIN" -i eth0 -p tcp --dport 53 -j ACCEPT || { B_ERR="iptables issue." ; B_E ; }
 }
 
 function resetFirewall {
@@ -207,11 +207,11 @@ echo "$ret"
 #stops the unbound daemon, if unbound is used
 function stopR {
 local pid=
-pid="$(getPid)" || { B_ERR="unbound appears to be stopped." ; B_E }
+pid="$(getPid)" || { B_ERR="unbound appears to be stopped." ; B_E ; }
 b_info "Stopping unbound..."
 resetFirewall
 restoreLocalDNSServer
-kill "$pid" || { B_ERR="Failed to terminate unbound (pid: $pid)." ; B_E }
+kill "$pid" || { B_ERR="Failed to terminate unbound (pid: $pid)." ; B_E ; }
 b_info "unbound was stopped."
 }
 
